# Generated by Django 3.1.4 on 2020-12-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201225_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field=400, upload_to='uploads/', width_field=400),
        ),
    ]
