# Generated by Django 3.1.4 on 2020-12-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='access',
            field=models.BooleanField(default=True),
        ),
    ]
